---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: video-repository-ui
  labels:
    app: video-repository-ui
    project: video-repository-ui

spec:
  replicas: 3
  selector:
    matchLabels:
      app: video-repository-ui
      project: video-repository-ui
  template:
    metadata:
      labels:
        app: video-repository-ui
        project: video-repository-ui
    spec:
      containers:
        - name: video-repository-ui
          image: oarepo-demo-ui:latest
          startupProbe:
            httpGet:
              path: /
              port: ui
            failureThreshold: 5
            timeoutSeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: ui
            timeoutSeconds: 15
            periodSeconds: 10
            failureThreshold:
            successThreshold:
          readinessProbe:
            httpGet:
              path: /
              port: ui
            timeoutSeconds: 15
            periodSeconds: 10
          env:
            - name: "OAREPO_POD_IP"
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: ui
              containerPort: 80
      imagePullSecrets:
        - name: CHANGE_THIS
