apiVersion: v1
kind: Service
metadata:
  name: video-repository-ui

spec:
  ports:
    - protocol: TCP
      name: ui
      port: 80
  selector:
    app: video-repository-ui
    project: video-repository-ui
